---
version: 2
multicolumn: false
web-width: 800
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/Uncertainties/Uncertainties.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/18589/articles/304710/master/file/figures/Uncertainties/Uncertainties.png"
    folder_url: "/users/18589/articles/304710/master/folder/figures/Uncertainties"
