---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/Residual_plot/residual_error.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    folder_url: "/users/18589/articles/304710/master/folder/figures/Residual_plot"
    url: "/users/18589/articles/304710/master/file/figures/Residual_plot/residual_error.png"
